apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: bW9uZ291c2Vy # base64 for "mongouser"
  mongo-root-password: bW9uZ29wYXNz # base64 for "mongopass"
